### PR TITLE
Bug/956/random buildings highlighted

### LINKED ISSUE #956: Hilighting in multiple mode broken - Random buildings highlighted
# Bug

## Expected Behavior

WHEN a folder is hovered in either the tree view or the map...

...THEN this folder and its contents should be highlighted

## Actual Behavior

In multiple mode, some random buildings and folders are highlighted instead

Example: In the screenshot below all folders/files in the "V" area should be highlighted and nothing in the "A" area, however instead random files/folders are highlighted.

## Screenshots

hilighting_broken

## Steps to Reproduce the Problem
1. Select multiple maps in multiple mode
1. Hilight a folder

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.47.1

### PR DESCRIPTION
**Pull request by JaiJoPa**
# Random buildings highlighted in multiple mode

_**Please read the [CONTRIBUTING.md](https://github.com/MaibornWolff/codecharta/blob/main/CONTRIBUTING.md) before opening a PR.**_

fixes #956 

## Description

- This PR solves the issue, that in multiple mode, random buildings are highlighted when hovering over the map or mapTree
- The Problem: two different maps can have the same Ids for the buildings, so in multiple mode the Id's are not unique anymore
- This PR moves the idDecorcation call from preDecorateFile to decorateMap
- That way the buildings get their unique ID's when the map changes

## Screenshots or gifs

multipleMode

### CODE REVIEW

File: visualization/app/codeCharta/util/nodeDecorator.ts [hunk 1]
```diff
@@ -27,7 +28,6 @@ export class NodeDecorator {
 
 	public static preDecorateFile(file: CCFile) {
 		this.decorateMapWithPathAttribute(file)
-		this.decorateNodesWithIds(file.map)
 	}
```
Comment (BridgeAR) [inline visualization/app/codeCharta/util/nodeDecorator.ts:31]: Keeping the `preDecorateFile()` function is probably not necessary anymore and we might instead call `decorateMapWithPathAttribute()` directly instead?

**Review by BridgeAR — APPROVED** [review]

File: visualization/app/codeCharta/util/nodeDecorator.ts (hunk 1 above)
Comment (NearW) [reply visualization/app/codeCharta/util/nodeDecorator.ts:31]: 100% agree

**Review by NearW — APPROVED** [review]
also approved after converting `preDecorateFile` to `decorateMapWithPaths`

**Comment by NearW** [comment]
@JaiJoPa oh, and please add a test simulating 2 maps in multiple are decorated and they should NOT have an id twice.

**Review by NearW — CHANGES_REQUESTED** [review]
regression test

File: visualization/app/codeCharta/ui/codeMap/codeMap.preRender.service.spec.ts [hunk 2]
```diff
@@ -201,5 +222,14 @@ describe("codeMapPreRenderService", () => {
 
 			expect(allNodesToBeExcluded()).toBeTruthy()
 		})
+
+		it("should change map to multiple mode and check that no id exists twice", () => {
+			const files = getCCFiles(storeService.getState().files)
+			storeService.dispatch(setMultiple(files))
```
Comment (NearW) [inline visualization/app/codeCharta/ui/codeMap/codeMap.preRender.service.spec.ts:228]: inline this, since files is only used once

```suggestion
			storeService.dispatch(setMultiple(getCCFiles(storeService.getState().files)))
```

**Review by NearW — APPROVED** [review]
LGTM otherwise
