### PR TITLE
Bug/1034/Persist color conversions to improve performance

### LINKED ISSUE #1034: Convert colors only once / only when necessary (performance)
Changing metrics triggers a huge amount of `convertHexToNumber` calls. In a big map this can easily add up to a significant time that is spend in that function. For the Apachge Open Office map it takes roughly 400 milliseconds on my device just in that function.

Ideally, the colors are precomputed and are only visualized for the user while clicking on a node / hovering above it, if necessary.

### PR DESCRIPTION
**Pull request by NearW**
# Persist color conversions to improve performance

closes #1034 

## Description

- Adds a map to store colorToVector3 conversions
- Adds a map to store hexToNumber conversions
- Replaces all occurences of conversions with checking the dedicated maps

@BridgeAR I wasn't able to notice a performance boost, but technically this should improve the performance by a lot. What map did you use to notice the huge amount of color conversions?

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [ ] **All** requirements mentioned in the issue are implemented
- [ ] Does match the Code of Conduct and the Contribution file
- [ ] Task has its own **GitHub issue** (something it is solving)
  - [ ] Issue number is **included in the commit messages** for traceability
- [ ] **Update the README.md** with any changes/additions made
- [ ] **Update the CHANGELOG.md** with any changes/additions made
- [ ] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [ ] **All tests pass**
- [ ] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [ ] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [ ] **Manual testing** did not fail

### CODE REVIEW

File: visualization/app/codeCharta/util/color/colorConverter.ts [hunk 1]
```diff
@@ -3,6 +3,25 @@ import convert from "color-convert"
...
 export class ColorConverter {
+	private static colorToVector3Map = new Map<string, Vector3>()
+	private static hexToNumberMap = new Map<string, number>()
+
+	public static getVector3(color: string): Vector3 {
+		if (!this.colorToVector3Map.has(color)) {
+			this.colorToVector3Map.set(color, ColorConverter.colorToVector3(color))
+		}
+
+		return this.colorToVector3Map.get(color)
```
Comment (BridgeAR) [inline visualization/app/codeCharta/util/color/colorConverter.ts:14]:
```suggestion
		let vector = this.colorToVector3Map.get(color)
		if (vector === undefined) {
			vector = ColorConverter.colorToVector3(color)
			this.colorToVector3Map.set(color, vector)
		}

		return vector
```

This reduces the lookups from two to one.

File: visualization/app/codeCharta/util/color/colorConverter.ts [hunk 2]
```diff
@@ -3,6 +3,25 @@ import convert from "color-convert"
...
+	}
+
+	public static getNumber(hex: string): number {
+		if (!this.hexToNumberMap.has(hex)) {
+			this.hexToNumberMap.set(hex, ColorConverter.convertHexToNumber(hex))
+		}
+
+		return this.hexToNumberMap.get(hex)
```
Comment (BridgeAR) [inline visualization/app/codeCharta/util/color/colorConverter.ts:22]:
```suggestion
		let number = this.hexToNumberMap.get(hex)
		if (number === undefined) {
			number = ColorConverter.convertHexToNumber(hex)
			this.hexToNumberMap.set(hex, number)
		}

		return number
```

**Comment by NearW** [comment]
@BridgeAR Thanks for the suggestion. At first I thought that such a small detail is not important, but considering the amount of call of this function really makes the little things here matter.

This needs another approve. :)
