### PR TITLE
Bug/542/Renaming breaks hierarchy in SVN log parser

### LINKED ISSUE #542: SVNLogParser hierarchy breaks due to rename
# Bug

## Expected Behavior
SVNLogParser should not create broken hierarchies when encountering rename information

### PR DESCRIPTION
**Pull request by alexhunziker**
# Renaming information in SVN log leads to wrong file attribution

closes #542 

## Description

- SVN Entries that contain renaming information are now attributed to the correct file
- SVNLogParser now keeps track of renaming, in order to correctly calculate metrics for renamed files
- Some refactoring of SVNLogParser and VersionControlled File. Exception is now thrown if file path+name are ambiguous in a commit
- Test cases (e2e) for svn + git parser to check correct renaming

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [ ] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

File: analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogNumstatRawParserStrategy.kt [hunk 1]
```diff
@@ -33,10 +33,10 @@ class GitLogNumstatRawParserStrategy: LogParserStrategy {
                 .filter { isFileLine(it) }
                 .map { parseModification(it) }
                 .groupingBy { it.filename }
-                .aggregate { _, mod1: Modification?, mod2, _ ->
-                    when (mod1) {
-                        null -> mergeModifications(mod2)
-                        else -> mergeModifications(mod1, mod2)
+                .aggregate { _, aggregatedModification: Modification?, currentModificatoin, _ ->
```
Comment (NearW) [inline analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/git/GitLogNumstatRawParserStrategy.kt]: typo currentModificatoin -> currentModification

File: analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/SVNLogParserStrategy.kt [hunk 2]
```diff
@@ -58,17 +58,35 @@ class SVNLogParserStrategy: LogParserStrategy {
...
+            else ->  parseStandardModification(trimmedFileLine, status)
+        }
+    }
+
+    private fun parseStandardModification(filePath: String, status: Status): Modification {
         return ignoreIfRepresentsFolder(Modification(filePath, status.toModificationType()))
     }
 
+    private fun parseRenameModification(filePathLine: String): Modification {
+        val fileNames = filePathLine.split(" (from")
```
Comment (NearW) [inline analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/SVNLogParserStrategy.kt]: RENAME_FILE_LINE_IDENTIFIER in split

File: analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/SVNLogParserStrategy.kt [hunk 3]
```diff
@@ -79,9 +97,10 @@ class SVNLogParserStrategy: LogParserStrategy {
 
     companion object {
 
+        private const val RENAME_FILE_LINE_IDENTIFIER =  " (from"
```
Comment (NearW) [inline analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/SVNLogParserStrategy.kt]: change to " (from "

File: analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/SVNLogParserStrategy.kt [hunk 4]
```diff
@@ -58,17 +58,35 @@ class SVNLogParserStrategy: LogParserStrategy {
...
+    }
+
+    private fun parseStandardModification(filePath: String, status: Status): Modification {
         return ignoreIfRepresentsFolder(Modification(filePath, status.toModificationType()))
     }
 
+    private fun parseRenameModification(filePathLine: String): Modification {
+        val fileNames = filePathLine.split(" (from")
+        val oldFileNameWithPrefix = fileNames.last().split(":").first()
+        val oldFileName = removeDefaultRepositoryFolderPrefix(oldFileNameWithPrefix.trim { it <= ' ' })
```
Comment (NearW) [inline analysis/import/SCMLogParser/src/main/kotlin/de/maibornwolff/codecharta/importer/scmlogparser/parser/svn/SVNLogParserStrategy.kt]: no trimming of prefix needed when IDENTIFIER is changed
