### PR TITLE
Bug/725/calculation distribution bar for excluded files

### LINKED ISSUE #725: File Extension Bar includes excluded files
# Bug

## Expected Behavior
Excluded files should not be considered when calculating the precertages in the file extension bar.

## Actual Behavior
Excluded files are not excluded from the calculation

### Screenshots
grafik

### PR DESCRIPTION
**Pull request by NearW**
# File-Extension-Bar will not display excluded nodes anymore

closes #725

## Description

- Boyscouted and refactored some minor things (See commit messages)
- Fixed #725

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by NearW** [comment]
I need some help with the following two files:
https://github.com/MaibornWolff/codecharta/pull/744/files#diff-4c726c8753a6486beea838272ffdc2e3
https://github.com/MaibornWolff/codecharta/pull/744/files#diff-6169394dcd88dd64eb9101f80ffd3f04

For some reason, the `isBlacklisted` method doesn't work correctly when I exclude a pattern like `*.java`, but when I do so in the app itself, everything works magically.
I assume, that there is something different with our test data maybe and empty spaces in file names, but I couldn't figure it out. Do you have an idea?

File: visualization/app/codeCharta/util/codeMapHelper.ts [hunk 1]
```diff
@@ -21,7 +20,14 @@ export class CodeMapHelper {
 	}
 
 	public static transformPath(toTransform: string): string {
-		return path.relative("/", toTransform)
+		let removeNumberOfCharactersFromStart = 0
+
+		if (toTransform.startsWith("./")) {
+			removeNumberOfCharactersFromStart = 2
+		} else if (toTransform[0] === "/") {
```
Comment (JaiJoPa) [inline visualization/app/codeCharta/util/codeMapHelper.ts]: Use here starts with too
