### PR TITLE
Bug/409/sliders truncate digits

### LINKED ISSUE #409: Sliders don't display all numbers
If I have a metric that is larger than 999 the (color) sliders only display the first three digits
![Screen Shot 2019-03-04 at 13.43.31[2].png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b45ff04882b29001104eeca/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206454f76b7191a379ec0c2f52415c4fc743354d58eeb9cb74fce36f34985619e883690b22c23818afe98616bc55ba208a1dd4b7e9834993fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee34d56a1143060ef733e6e0a.png)

Please enable CC to show (color) slider numbers up to 99.999.

### PR DESCRIPTION
**Pull request by alexhunziker**
# Input Fields for rangeSlider now adjust width according to content

closes #409 
Merge permission: {CC-Member | @member}

## Description

- Input Fields (From/To) for range slider now adjust in width depending on the number of digits they contain.

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [x] **All** requirements mentioned in the issue are implemented
* [x] Does match the Code of Conduct and the Contribution file 
* [x] Task has its own **GitHub issue** (something it is solving)
  * [x] Issue number is **included in the commit messages** for traceability
* [x] **Update the README.md** with any changes/additions made
* [x] **Update the CHANGELOG.md** with any changes/additions made
* [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
* [x] **All tests pass**    
* [x] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [x] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by alschmut** [comment]
I think we should also add a maximum width. And another idea I had. How about only setting a `MIN_DIGITS` and a `MAX_DIGITS` and calculate the actual pixel with width `DIGIT_WIDTH` afterwards. So the constants make more sense when reading the code ;) I guess we can set `MIN_DIGITS` to 4 and `MAX_DIGITS` maybe to 6

**Comment by alexhunziker** [comment]
Yes, that looks silly, I added a maximum width for the fields.

File: visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.ts [hunk 1]
```diff
@@ -71,10 +72,10 @@ export class RangeSliderController implements SettingsServiceSubscriber {
 	}
 
 	private updateInputFieldWidth() {
-		let fromLength = this.settingsService.settings.neutralColorRange.from.toFixed().toString().length
-		let toLength = this.settingsService.settings.neutralColorRange.to.toFixed().toString().length
-		let fromWidth = Math.max((fromLength + 1) * this.DIGIT_LENGTH, this.STANDARD_WIDTH_RANGE_INPUT)
-		let toWidth = Math.max((toLength + 1) * this.DIGIT_LENGTH, this.STANDARD_WIDTH_RANGE_INPUT)
+		let fromLength = this.settingsService.settings.neutralColorRange.from.toFixed().toString().length + 1
```
Comment (alschmut) [inline visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.ts]: Do we actually need the `toFixed()`?

Comment (alexhunziker) [reply visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.ts]: I added this there because when a map is loaded, sometimes the calculated values are not whole numbers/integers. This can cause the inputFields to be to wide when opening the ribbon bar for the first time after import.

Comment (alschmut) [reply visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.ts]: Alright ;)
