### PR TITLE
Bug/631/out of memory scm

### LINKED ISSUE #631: OutOfMemory Error and Performance SCMLogParser
# Bug

## Actual Behavior
For a large GitLog (~90MB) the parser fails after working for 15 minutes or so with a `java.lang.OutOfMemoryError: Java heap space` exception.
(If the heap size is increased manually an `java.lang.OutOfMemoryError: GC overhead limit exceeded` exception is thrown)

## Expected Behaviour
No exception should be thrown, also maybe we can add a progress indicator and/or increase the performance of the parser

## Reproduction

Please ask Christian for the Log file he used to reproduce the issue

## Specifications

  - Version: 1.28
  - Platform: Windows

### PR DESCRIPTION
**Pull request by alexhunziker**
# Fixing OutOfMemory exception for large log files in SCMLogParser

closes #631

## Description

- Added Progress indicator for SCMLogParser
- The highly coupled files metric is now calculated only after all commits have been parsed, this allows for a less memory intensive computation of the metric

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

- [x] **All** requirements mentioned in the issue are implemented
- [x] Does match the Code of Conduct and the Contribution file
- [x] Task has its own **GitHub issue** (something it is solving)
  - [x] Issue number is **included in the commit messages** for traceability
- [x] **Update the README.md** with any changes/additions made
- [x] **Update the CHANGELOG.md** with any changes/additions made
- [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
- [x] **All tests pass**
- [x] **Descriptive pull request text**, answering:
  - What problem/issue are you fixing?
  - What does this PR implement and how?
- [x] **Assign your PR to someone** for a code review
  - This person _will be contacted **first**_ if a bug is introduced into `master`
- [x] **Manual testing** did not fail

### CODE REVIEW

**Comment by Richargh** [comment]
@alexhunziker while you take a look at the scmlogparser: can you make sure progress and other information is only logged to the console error stream. The regular console output should be reserved for cc.json contents solely.

File: analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/ProjectBuilder.kt [hunk 1]
```diff
@@ -100,6 +100,7 @@ open class ProjectBuilder(
                 blacklist = blacklist.toList()
         )
 
+        System.err.println()
```
Comment (NearW) [inline analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/ProjectBuilder.kt]: Is this necessary?

Comment (alexhunziker) [reply analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/ProjectBuilder.kt]: Well otherwise you have the log entry starting on the same line as the progress indicator - which looks odd

Comment (alexhunziker) [reply analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/ProjectBuilder.kt]: ... and unfortunately it does not work to let the log message (line 104) start with \n...
