### PR TITLE
Fix command not found error by changing execution logic

### LINKED ISSUE #3356: ccsh arguments like --version are not working anymore
# Bug

## Expected Behavior

<GIVEN>

WHEN
running `ccsh --version` or `ccsh -h`

THEN
the corresponding version / help message is shown

## Actual Behavior
An error message occurs

## Screenshots
image

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): -
- CodeCharta Version: 1.119.0
- OS: Windows
- Browser: -

### PR DESCRIPTION
**Pull request by phanlezz**
# Fix for command not found error

Add regression test

Closes #3356

### CODE REVIEW

File: analysis/test/golden_test.sh [hunk 1]
```diff
@@ -171,6 +171,30 @@ check_pipe() {
   fi
 }
 
+check_help() {
```
Comment (ce-bo) [inline analysis/test/golden_test.sh:174]: Thank you for adding regression tests <3

**Review by ce-bo — APPROVED** [review]
LGTM :-)
